#!/bin/bash
echo "=========================="
echo "       LLVM Builder"
echo "    by Nakada Tokumei"
echo "=========================="

if [[ ! -d build/ ]]; then
    mkdir build/
fi

cd build/

cmake -G Ninja ../llvm                                          \
    -DLLVM_ENABLE_PROJECTS="clang;lld"                          \
    -DCMAKE_BUILD_TYPE=Release                                  \
    -DLLVM_TARGETS_TO_BUILD="X86"                               \
    -DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-pc-linux-gnu"          \
    -DLLVM_ENABLE_ASSERTATIONS=ON

ninja -j8
